spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docker-exempel
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
